### ISSUE TITLE
Icons for dwmblocks-enhanced

### ISSUE THREAD

**Issue by IamGianluca** [onur-ozkan/nixconf#2]
Hi, 

I like your setup for `dwmblocks` that you shared on Reddit. Unfortunately, GitHub is not rendering the icons you used for the scripts used by `dwmblocks`. Would you mind share a link to the icon set?

Would you mind also sharing how you could make the icons display on your `dwmblocks`? I've tried to use other icons temporarily, and whilst they render on `gnome-terminal`, they don't render in either `st` nor `dwmblocks`.

Many thanks,
Luca

**Comment by onur-ozkan** [comment]
Hello @IamGianluca ,

> I like your setup for dwmblocks that you shared on Reddit. Unfortunately, GitHub is not rendering the icons you used for the scripts used by dwmblocks. Would you mind share a link to the icon set?

You can clone the repository and then check the icons, or directly copy paste them(doesn't matter if Github is not rendering, you can still copy-paste them).

> Would you mind also sharing how you could make the icons display on your dwmblocks? I've tried to use other icons temporarily, and whilst they render on gnome-terminal, they don't render in either st nor dwmblocks.

Which font are you using for dwmblocks and st? Font type needs to support icons you want to use. Check this out https://www.nerdfonts.com

**Comment by IamGianluca** [comment]
Hi @ozkanonur,

Thank you for getting back to me so quickly! You're right, Nerd Fonts fixed the issue. I'm still unable to render the different colors on `dwmblocks`, but I will study your `dwm` config to learn how that works.

**Comment by onur-ozkan** [comment]
You have to apply https://dwm.suckless.org/patches/statuscolors/ this patch to your dwm first. Then check [this scripts](https://github.com/ozkanonur/dotfiles/tree/master/.local/bin/statusbar) to understand how to print in color.

**Comment by IamGianluca** [comment]
Thank you very much! I really appreciate it :+1:
